# Generated by Django 2.0.8 on 2018-10-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('number_suffix', models.CharField(default='', max_length=64, verbose_name='Suffix of number')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('number_type', models.CharField(default='', max_length=64, verbose_name='Root part of number')),
                ('high_root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.Root', verbose_name='Root of type')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('number_type', models.CharField(default='', max_length=64, verbose_name='Type part of number')),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.Root', verbose_name='Root of type')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.Layer', verbose_name='Layer of item'),
        ),
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.Item', verbose_name='Where is Item?'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.Type', verbose_name='Type of item'),
        ),
    ]
