# Generated by Django 2.0.8 on 2018-10-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.Item', verbose_name='Where is Item?'),
        ),
        migrations.AlterField(
            model_name='root',
            name='high_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.Root', verbose_name='Root of type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.Root', verbose_name='Root of type'),
        ),
    ]
