# Generated by Django 2.0.8 on 2018-10-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_auto_20181026_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='type',
            name='type_separator',
            field=models.CharField(blank=True, default='\\', max_length=64, verbose_name='Separator for path of this type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='prefix_suffix_separator',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Separator for number of this type'),
        ),
    ]
