# Generated by Django 2.0.8 on 2018-10-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0005_auto_20181026_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type_separator',
            new_name='path_separator',
        ),
        migrations.RemoveField(
            model_name='type',
            name='prefix_suffix_separator',
        ),
        migrations.AddField(
            model_name='type',
            name='item_separator',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Item separator for number of this type'),
        ),
    ]
