# Generated by Django 2.0.8 on 2018-10-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0006_auto_20181026_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_separator',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Separator for prefix of this type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='item_separator',
            field=models.CharField(blank=True, default='-', max_length=64, verbose_name='Item separator for number of this type'),
        ),
    ]
