# Generated by Django 2.0.8 on 2018-10-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_auto_20181026_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['root_path']},
        ),
        migrations.AddField(
            model_name='type',
            name='root_path',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Tree_path'),
        ),
    ]
