# Generated by Django 2.1.2 on 2018-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0009_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='place_path',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Place tree path'),
        ),
        migrations.AlterField(
            model_name='type',
            name='root_path',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Tree path'),
        ),
    ]
