# Generated by Django 2.1.2 on 2018-11-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0011_auto_20181106_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='layer',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
    ]
