# Generated by Django 2.1.2 on 2018-11-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0012_auto_20181106_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=64)),
                ('secondary', models.CharField(max_length=64)),
                ('tertiary', models.CharField(max_length=64)),
            ],
        ),
    ]
