# Generated by Django 2.1.2 on 2018-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='finder',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='String for finder, autocomplete'),
        ),
    ]
