# Generated by Django 2.1.2 on 2018-11-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0015_item_finder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(blank=True, default='', help_text='ex: "text=book+magazine"', max_length=1024)),
                ('is_up_button', models.BooleanField(default=False, help_text='Is it up button?')),
                ('icon_class', models.CharField(blank=True, default='', help_text='ex: "fas fa-car"', max_length=64)),
                ('is_down_link', models.BooleanField(default=False, help_text='Is it down link?')),
                ('link_text', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
