# Generated by Django 2.1.2 on 2018-11-18 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystore', '0016_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='order_index',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, help_text="set User only if it's personal request", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='query_text',
            field=models.CharField(blank=True, default='', help_text='exs: "text=book+magazine"  "type=4"  "types=4"  "itemcontent=12"', max_length=1024),
        ),
    ]
