# Generated by Django 2.1.2 on 2018-11-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0017_auto_20181118_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color_palette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.ColorPalette'),
        ),
    ]
